
/******************************************************************************\
*       This is a part of the Microsoft Source Code Samples. 
*       Copyright (C) 1993 Microsoft Corporation.
*       All rights reserved. 
*       This source code is only intended as a supplement to 
*       Microsoft Development Tools and/or WinHelp documentation.
*       See these sources for detailed information regarding the 
*       Microsoft samples programs.
\******************************************************************************/

/*************************************************************\
* world.h: Header file for WORLD sample                       *
*                                                             *
*                                                             *
\*************************************************************/


/******* Menu Defines *******/

//#define IDM_OPEN       1000
//#define IDM_EXIT       1001
#define IDM_SCALE      1002
//#define IDM_ABOUT      1003


/***** Control Defines ******/

#define IDC_HORZ       2000
#define IDC_VERT       2001

#define IDM_NEW            100
#define IDM_OPEN           101
#define IDM_SAVE           102
#define IDM_SAVEAS         103
#define IDM_PRINT          104
#define IDM_PRINTSETUP     105
#define IDM_EXIT           106
#define IDM_UNDO           200
#define IDM_CUT            201
#define IDM_COPY           202
#define IDM_PASTE          203
#define IDM_LINK           204
#define IDM_LINKS          205
#define IDM_HELPCONTENTS   300
#define IDM_HELPSEARCH     301
#define IDM_HELPHELP       302
#define IDM_ABOUT          303

#define DLG_VERFIRST        400
#define DLG_VERLAST         404
